//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControldeUsuarios.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class INDIVIDUO3
    {
        [Display(Name = "#")]
        public int Id_individuo { get; set; }
        [Display(Name = "Nombre de la persona")]
        public string Nombre { get; set; }
        [Display(Name = "Apellido de la persona")]
        public string Apellido { get; set; }
        [Display(Name = "Edad de la persona")]
        public Nullable<int> Edad { get; set; }
        [Display(Name = "Correo de la persona")]
        public string Correo { get; set; }
    }
}
